name: adventures_in_meetups
description: A Flutter web app for the Adventures In [Dart, Flutter, Firebase] Meetup group.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  firebase_auth: any

  ferry: ^0.10.2+2
  gql_http_link: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  ferry_generator: ^0.4.2
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
