name: adventures_in_meetups
description: A Flutter web app for the Adventures In [Dart, Flutter, Firebase] Meetup group.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
